name: Check Env

on:
  push:
    branches:
      - main

jobs:
  check-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # ou la version que tu utilises


      - name: Exécuter le script check-env.sh
        run: |
          chmod +x check-env.sh
          ./check-env.sh
